FLAGS := -g -w

QF:
	g++ -c cod/QF.c $(FLAGS)
	g++ -c main.c $(FLAGS)
	g++ -o main *.o $(FLAGS)
	rm *.o

QU:
	g++ -c cod/QU.c $(FLAGS)
	g++ -c main.c $(FLAGS)
	g++ -o main *.o $(FLAGS)
	rm *.o

QU_W_PC:
	g++ -c cod/QU_W_PC.c $(FLAGS)
	g++ -c main.c $(FLAGS)
	g++ -o main *.o $(FLAGS)
	rm *.o