FLAGS := -g -w

crivo:
	g++ -c cod/crivo.c $(FLAGS)
	g++ -c crivo.c $(FLAGS)
	g++ -o main *.o $(FLAGS)
	rm *.o

josefo:
	g++ -c cod/josefo.c $(FLAGS)
	g++ -c josefo.c $(FLAGS)
	g++ -o main *.o $(FLAGS)
	rm *.o
	
dijkstra:
	g++ -c dijkstra.c $(FLAGS)
	g++ -c pilha/pilha.c $(FLAGS)
	g++ -o main *.o $(FLAGS)
	rm *.o