FLAGS := -g -w

desbalanceada:
	g++ -c arvore/arvore.c $(FLAGS)
	g++ -c pilha/pilha.c $(FLAGS)
	g++ -c fila/fila.c $(FLAGS)
	g++ -c desbalanceada.c $(FLAGS)
	g++ -o main *.o $(FLAGS)
	rm *.o

caminhamento:
	g++ -c arvore/arvore.c $(FLAGS)
	g++ -c pilha/pilha.c $(FLAGS)
	g++ -c fila/fila.c $(FLAGS)
	g++ -c caminhamento.c $(FLAGS)
	g++ -o main *.o $(FLAGS)
	rm *.o